# NumPy

##### What is NumPy?
NumPy is a Python library for numerical computing that provides efficient operations on multi-dimensional arrays and matrices, along with a wide range of mathematical functions.

##### Why use NumPy?
In Python, lists are slower and consume more memory due to their dynamic nature. NumPy arrays are significantly faster, memory-efficient, and optimized for large-scale numerical computations.

##### Who uses NumPy?
Data scientists, data engineers, machine learning practitioners, and researchers rely on NumPy for data manipulation, numerical analysis, and scientific computing.

##### Where is NumPy used?
NumPy is used in various fields, such as machine learning, data analysis, scientific simulations, and as a foundation for libraries like Pandas and TensorFlow.

##### When to use NumPy?
NumPy is ideal for tasks involving large-scale numerical data or mathematical operations that demand efficiency, speed, and precision.

##### How does NumPy work?
NumPy uses an n-dimensional array object implemented in C to perform fast, memory-efficient numerical computations directly on arrays, outperforming Python's native data structures.

### Content
1. Introduction
2. Installation
3. Importing NumPy
4. Creating Array
5. Initializing Array
6. Array Properties
7. Array Operations
8. ---END---

# 1. Introduction
• NumPy is a Python library used for working with arrays.

• NumPy is a library consisting of multidimensional array objects and a collection of routines for processing the arrays

• In Python we have lists that serve the purpose of arrays, but they are slow to process.

• NumPy aims to provide an array object which works faster than traditional Python lists.

• NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

# 3. Importing Numpy

In [1]:
import numpy as np
print(np.__version__)

1.26.4


# 4. Creating Array's
--> 4 way's to create array's in numpy
- array()
  * 0-Dimentional Arrays    --> 0D: Single value (scalar).
  * 1-Dimentional Arrays    --> 1D: List of elements (vector).
  * 2-Dimentional Arrays    --> 2D: Matrix (rows and columns).
  * 3-Dimentional Arrays    --> 3D: Array of matrices (depth).
- asarray() with nditer()
- frombuffer()
- fromiter()

### 1st Method of creating NumPy Array's --> array()

In [2]:
# 0-Dimensional Arrays (Scalar Array)
# 0-dimensional array contains a single value (scalar). It is essentially just a value wrapped in an array.
import numpy as np

arr_0d = np.array(42)
print("0-Dimensional Array:")
print(arr_0d)
print("Shape:", arr_0d.shape)

# Here, arr_0d contains just the scalar value 42, and the shape is (), indicating it has no dimensions.

0-Dimensional Array:
42
Shape: ()


In [3]:
# 1-Dimensional Arrays
# A 1-dimensional array is essentially a list or vector with one row of values.

arr_1d = np.array([1, 2, 3])
print("1-Dimensional Array:")
print(arr_1d)
print("Shape:", arr_1d.shape)

# The shape (3,) indicates the array has one dimension with 3 elements.


1-Dimensional Array:
[1 2 3]
Shape: (3,)


In [4]:
# 2-Dimensional Arrays (Matrix)
# A 2-dimensional array is a matrix, where data is arranged in rows and columns.

arr_2d = np.array([[1, 2], [3, 4]])
print("2-Dimensional Array:")
print(arr_2d)
print("Shape:", arr_2d.shape)

# The shape (2, 2) indicates the array has 2 rows and 2 columns.

2-Dimensional Array:
[[1 2]
 [3 4]]
Shape: (2, 2)


In [5]:
# 3-Dimensional Arrays
# A 3-dimensional array extends a 2D array by adding depth, like a cube of data.

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3-Dimensional Array:")
print(arr_3d)
print("Shape:", arr_3d.shape)

# The shape (2, 2, 2) indicates the array has 2 blocks (depth), each with 2 rows and 2 columns.

3-Dimensional Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


### 2nd Method of creating NumPy Array's --> asarray()
The asarray() function in NumPy is used to convert an input (such as a list or a tuple) into a NumPy array, but it will not copy the data if the input is already a NumPy array. You can use nditer() to iterate over the elements of an array efficiently.

In [6]:
import numpy as np

# Creating a list of lists
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]      # it is list

print("data =",data)
print("Type =",type(data))
print('---------------------------------------------')
# Convert the list of lists into a NumPy array using asarray()
arr = np.asarray(data,order='f')    # converting list of list into numpy array # here we can give f: column wise, c: row wise asarray(data,order='r')
print("NumPy Array = \n",arr)
print("Type =",type(arr))
print('---------------------------------------------')
# Use nditer to iterate over the elements of the array
print("Iterating over the array elements:")
for x in np.nditer(arr):
    print(x)

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Type = <class 'list'>
---------------------------------------------
NumPy Array = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Type = <class 'numpy.ndarray'>
---------------------------------------------
Iterating over the array elements:
1
4
7
2
5
8
3
6
9


### 3rd Method of creating NumPy Array's --> frombuffer()
- The frombuffer() function in NumPy is used to create an array from a buffer (a string, bytes, or binary data). It reads data from a file-like object or buffer and converts it into a NumPy array.
- Syntax : **numpy.frombuffer(buffer, dtype=float, count=-1, offset=0)**
  * buffer: The data (in bytes) to convert into an array.
  * dtype: The desired data type of the array (default is float).
  * count: The number of elements to read. The default (-1) reads the entire buffer.
  * offset: The number of bytes to skip before starting to read data (default is 0).

In [7]:
import numpy as np

# Create a binary buffer (e.g., bytes representing integers)
buffer = b'\x01\x02\x03\x04\x05\x06'

# Create a NumPy array from the binary buffer
arr = np.frombuffer(buffer, dtype=np.uint8)

print("Array from buffer:")
print(arr)

Array from buffer:
[1 2 3 4 5 6]


**Explanation:**
- Buffer: We created a bytes object buffer = b'\x01\x02\x03\x04\x05\x06' where each pair of hexadecimal digits represents an 8-bit number.
- frombuffer(): The function reads this buffer and converts it into a NumPy array of unsigned 8-bit integers (np.uint8).
- Result: The output is a NumPy array [1, 2, 3, 4, 5, 6], where each byte in the buffer is interpreted as an individual element.                        

**Use Case:**                                                                                                                                           
frombuffer() is useful for reading data from binary files or raw byte streams. It is especially helpful in situations where you have to parse large datasets stored in binary format (e.g., files with raw sensor data or images).

### 4th Method of creating NumPy Array's --> fromiter()
- The fromiter() function in NumPy is used to create a NumPy array from an iterable object, such as a list, tuple, or generator. This function allows for the creation of an array from an iterable without first converting it to a list, making it efficient for large or dynamic datasets.

Syntax : **numpy.fromiter(iterable, dtype=float, count=-1)**
- iterable: The iterable object (e.g., list, tuple, or generator) from which the array is created.4
- dtype: The desired data type of the resulting array (default is float).
- count: The number of items to read from the iterable. The default (-1) reads the entire iterable.

In [8]:
import numpy as np

# Create a generator (iterable)
def generate_numbers():
    for i in range(1, 6):
        yield i

# Create a NumPy array from the generator using fromiter
arr = np.fromiter(generate_numbers(), dtype=np.int32)

print("Array from iterable:")
print(arr)

Array from iterable:
[1 2 3 4 5]


**Explanation:**
- Iterable (generate_numbers): We define a generator function generate_numbers() that yields numbers from 1 to 5. Generators are a type of iterable that allow for on-the-fly data generation without storing the entire sequence in memory.
- fromiter(): We pass the generator generate_numbers() to np.fromiter(), which creates a NumPy array from this iterable.
- Result: The output is a NumPy array [1, 2, 3, 4, 5].

**Why use fromiter()?**
- Efficiency: If the iterable is large or dynamically generated (e.g., data streamed from a file or network), using fromiter() is memory efficient as it does not require storing the entire iterable in memory first.
- Simplicity: It directly converts an iterable to a NumPy array without the need to create an intermediate list.

**Use Case:**
- Dynamic Data Processing: When you are dealing with a stream of data or large datasets that don't fit entirely in memory, you can use fromiter() to create arrays directly from iterators or generators.

**Conclusion:**
- fromiter() is useful when working with iterables (including generators) and when you want to efficiently create NumPy arrays without loading all data into memory beforehand.

# 5. Initializing Array

**Array Initialization:**
- zeros(): Array filled with zeros.
- full(): Array filled with a specified value.
- random.rand(): Array with random numbers between 0 and 1.
- ones(): Array filled with ones.
- eye(): Identity matrix.
- empty(): Array with uninitialized values.
- identity(): Identity matrix.

**Numerical Ranges:**
- arange(): Array with values in a specified range.
- linspace(): Array with evenly spaced values over a range.
- logspace(): Array with logarithmic spacing.
- meshgrid(): Coordinate grid arrays.
- flip(): Reverse the order of elements in an array.


In [9]:
# Initializing Arrays in NumPy:

# zeros():
# Creates an array filled with zeros.
# Syntax: np.zeros(shape, dtype=float)

arr = np.zeros((2, 3))
print('Zeros')
print(arr)
print('-------------------------------')
# full():
# Creates an array filled with a specific value.
# Syntax: np.full(shape, fill_value, dtype=None)

arr = np.full((2, 3), 7)
print('Full with 7 num')
print(arr)
print('-------------------------------')

# random.rand():
# Creates an array with random values between 0 and 1.
# Syntax: np.random.rand(d0, d1, ..., dn)

arr = np.random.rand(2, 3)
print('rondom numbers b/w 0 to 1 in 2 rows & 3 columns')
print(arr)
print('-------------------------------')
# ones():
# Creates an array filled with ones.
# Syntax: np.ones(shape, dtype=float)

arr = np.ones((3, 2))
print('all ones in 3X2')
print(arr)
print('-------------------------------')
# eye():
# Creates an identity matrix (ones on the diagonal, zeros elsewhere).
# Syntax: np.eye(N, M=None, dtype=float)

arr = np.eye(3)
print('identity matrix : all ones in diagonal at 3X3')
print(arr)
print('-------------------------------')
# empty():
# Creates an uninitialized array (the values are random/garbage).
# Syntax: np.empty(shape, dtype=float)

arr = np.empty((2, 3))
print('uninitialized array (the values are random/garbage).')
print(arr)
print('-------------------------------')
# identity():
# Creates an identity matrix (similar to eye(), but can also handle non-square matrices).
# Syntax: np.identity(n, dtype=float)

arr = np.identity(3)
print('identity matrix : all ones in diagonal at 3X3')
print(arr)

Zeros
[[0. 0. 0.]
 [0. 0. 0.]]
-------------------------------
Full with 7 num
[[7 7 7]
 [7 7 7]]
-------------------------------
rondom numbers b/w 0 to 1 in 2 rows & 3 columns
[[0.12650337 0.44626805 0.38265165]
 [0.44018153 0.87525151 0.67785349]]
-------------------------------
all ones in 3X2
[[1. 1.]
 [1. 1.]
 [1. 1.]]
-------------------------------
identity matrix : all ones in diagonal at 3X3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-------------------------------
uninitialized array (the values are random/garbage).
[[1. 1. 1.]
 [1. 1. 1.]]
-------------------------------
identity matrix : all ones in diagonal at 3X3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# Numerical Ranges in NumPy:


# arange():
# Creates an array with values within a specified range, with a specified step size.
# Syntax: np.arange(start, stop, step)

arr = np.arange(0, 10, 2)
print('arange')
print(arr)
print('-------------------------------')
# linspace():
# Creates an array with evenly spaced values over a specified range.
# Syntax: np.linspace(start, stop, num=50, endpoint=True)

arr = np.linspace(0, 1, 5)
print('linespace')
print(arr)
print('-------------------------------')
# logspace():
# Creates an array with logarithmically spaced values over a specified range.
# Syntax: np.logspace(start, stop, num=50, endpoint=True, base=10.0)

arr = np.logspace(1, 3, 3)
print('longspace')
print(arr)
print('-------------------------------')
# meshgrid():
# Creates coordinate matrices from coordinate vectors.
# Syntax: np.meshgrid(x, y)

x = np.linspace(0, 5, 3)
y = np.linspace(0, 5, 3)
X, Y = np.meshgrid(x, y)
print('meshgrid')
print(arr)
print('-------------------------------')
# flip():
# Reverses the order of elements in an array along a specified axis.
# Syntax: np.flip(a, axis=None)

arr = np.array([1, 2, 3, 4])
flipped_arr = np.flip(arr)
print('fliparray')
print(arr)

arange
[0 2 4 6 8]
-------------------------------
linespace
[0.   0.25 0.5  0.75 1.  ]
-------------------------------
longspace
[  10.  100. 1000.]
-------------------------------
meshgrid
[  10.  100. 1000.]
-------------------------------
fliparray
[1 2 3 4]


# 6. Array Properties

- SIZE: Total number of elements in the array.
- SHAPE: Dimensions of the array (number of rows, columns, etc.).
- DTYPE: Data type of the elements in the array.
- ITEMSIZE: Size (in bytes) of one element in the array.
- NDIM: Number of dimensions of the array.
- T: Transposed version of the array (flips rows and columns).
- BASE: Base object if the array is a view.
- REAL/IMAG: Real and imaginary parts of complex arrays.
- FLAT: 1-D iterator over the array (flattened array).

In [11]:
# 1. SIZE:
# Returns the total number of elements in the array.
# It’s equivalent to the number of elements in the array, which is calculated as the product of the dimensions (shape).
# Syntax: array.size
print('SIZE')
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.size)
print('--------------------------------------------')
 
# 2. SHAPE:
# Returns a tuple representing the dimensions (shape) of the array. It gives the size of the array along each dimension.
# For a 2D array, it returns (rows, columns), and for a 3D array, it returns (depth, rows, columns).
# Syntax: array.shape
print('SHAPE')
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print('--------------------------------------------')

# 3. DTYPE:
# Returns the data type (dtype) of the array, i.e., the type of elements in the array (e.g., int64, float64).
# NumPy arrays can hold different types of data (integers, floats, complex numbers, etc.).
# Syntax: array.dtype
print('DTYPE')
import numpy as np
arr = np.array([1.5, 2.3, 3.1])
print(arr.dtype)
print('--------------------------------------------')

# 4. ITEMSIZE:
# Returns the size (in bytes) of one element in the array.
# Syntax: array.itemsize
print('ITEMSIZE')
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.itemsize)
print('--------------------------------------------')

# 5. NDIM:
# Returns the number of dimensions (axes) of the array.
# Syntax: array.ndim
print('NDIM')
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(arr.ndim)
print('--------------------------------------------')

# 6. T (Transpose):
# Returns a transposed view of the array (flips rows and columns).
# For a 2D array, it switches the rows with the columns.
# Syntax: array.T
print('TRANSPOSE')
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.T)
print('--------------------------------------------')

# 7. BASE:
# Returns the base object if the array is a view of another array, or None if it is not a view.
# Syntax: array.base
print('BASE')
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = arr1[1:]
print(arr2.base)  # It will return arr1, because arr2 is a view of arr1
print('--------------------------------------------')

# 8. REAL & IMAG:
# These properties return the real and imaginary parts of the array, respectively (useful for complex arrays).
# Syntax: array.real, array.imag
print('REAL & IMAG')
import numpy as np
arr = np.array([1+2j, 3+4j, 5+6j])
print(arr.real)
print(arr.imag)
print('--------------------------------------------')

# 9. FLAT:
# Returns a 1-D iterator over the array. It allows you to iterate through the elements of an array in a flattened manner (i.e., treating the array as a 1D structure).
# Syntax: array.flat
print('FLAT')
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for item in arr.flat:
    print(item)

SIZE
6
--------------------------------------------
SHAPE
(2, 3)
--------------------------------------------
DTYPE
float64
--------------------------------------------
ITEMSIZE
4
--------------------------------------------
NDIM
2
--------------------------------------------
TRANSPOSE
[[1 4]
 [2 5]
 [3 6]]
--------------------------------------------
BASE
[1 2 3]
--------------------------------------------
REAL & IMAG
[1. 3. 5.]
[2. 4. 6.]
--------------------------------------------
FLAT
1
2
3
4
5
6


# 7. Array Operations

**1. Accessing and Slicing Operations :**

1. copy(): Creates a new array that does not share memory with the original array.
2. view(): Creates a view of the original array; changes in one affect the other.
3. sort(): Sorts elements in ascending order along a specified axis.
4. reshape(): Changes the shape of an array without modifying its data.
5. append(): Adds new elements to the end of an array, creating a new array.
6. insert(): Inserts values into an array at specified positions along an axis.
7. delete(): Removes elements from an array along a specified axis.
8. concatenate(): Joins multiple arrays into a single array along a specified axis.
9. stack(): Combines arrays along a new axis.
10. vstack(): Vertically stacks arrays (row-wise).
11. hstack(): Horizontally stacks arrays (column-wise).
12. dstack(): Stacks arrays along the third (depth) axis.
13. split(): Divides an array into multiple sub-arrays.
14. where(): Returns indices of elements that satisfy a condition.
15. searchsorted(): Finds the index where elements should be inserted to maintain order.
16. Additional Array Operations
17. flatten(): Converts a multi-dimensional array into a 1D array.
18. ravel(): Similar to flatten(), but returns a view when possible.
19. transpose(): Reverses or permutes the axes of an array.
20. unique(): Extracts unique elements from an array, optionally with counts or indices.
21. argmax(): Returns the index of the maximum value in the array.
22. argmin(): Returns the index of the minimum value in the array.
23. tile(): Repeats the entire array a specified number of times.
24. repeat(): Repeats elements of an array individually a specified number of times.
25. clip(): Limits the values in an array within a specified range.
26. max(): Finds the maximum value in the array.
27. min(): Finds the minimum value in the array.
28. sum(): Calculates the sum of array elements along a specified axis.
29. mean(): Calculates the average of array elements.
30. cumsum(): Computes the cumulative sum of array elements.
31. prod(): Computes the product of all array elements along a specified axis.
32. cumprod(): Computes the cumulative product of array elements.

**2. Arithmetic Operations:**

1. add(): Adds two arrays element-wise.
2. subtract(): Subtracts one array from another element-wise.
3. multiply(): Multiplies two arrays element-wise.
4. divide(): Divides one array by another element-wise.
5. power(): Raises the elements of one array to the power of the corresponding elements of another array.
6. mod(): Computes the remainder of division of two arrays element-wise.
7. sqrt(): Computes the square root of each element.
8. abs(): Computes the absolute value of each element.
9. exp(): Computes the exponential (e^x) of each element.
10. log(): Computes the natural logarithm of each element.
11. log10(): Computes the base-10 logarithm of each element.
12. sin(): Computes the trigonometric sine of each element (in radians).
13. cos(): Computes the trigonometric cosine of each element (in radians).
14. tan(): Computes the trigonometric tangent of each element (in radians).

**3. Comparison Operations:**

1. greater(): Returns a boolean array where True represents if one element is greater than the other.
2. greater_equal(): Returns a boolean array where True represents if one element is greater than or equal to the other.
3. less(): Returns a boolean array where True represents if one element is less than the other.
4. less_equal(): Returns a boolean array where True represents if one element is less than or equal to the other.
5. equal(): Returns a boolean array where True represents if elements are equal.
6. not_equal(): Returns a boolean array where True represents if elements are not equal.
7. logical_and(): Performs a logical AND operation between arrays element-wise.
8. logical_or(): Performs a logical OR operation between arrays element-wise.
9. logical_not(): Performs a logical NOT operation on an array element-wise.

**4. Statistical Operations:**

1. std(): Computes the standard deviation of array elements.
2. var(): Computes the variance of array elements.
3. median(): Computes the median of array elements.
4. corrcoef(): Computes the Pearson correlation coefficient between two arrays.
5. cov(): Computes the covariance matrix between two arrays.

**5. Set Operations:**

1. union1d(): Computes the union of two arrays.
2. intersect1d(): Computes the intersection of two arrays.
3. setdiff1d(): Computes the difference between two arrays.
4. setxor1d(): Computes the symmetric difference between two arrays.

**6. Linear Algebra Operations:**

1. dot(): Computes the dot product of two arrays.
2. matmul(): Matrix multiplication of two arrays.
3. cross(): Computes the cross product of two arrays.
4. inv(): Computes the inverse of a square matrix.
5. eig(): Computes the eigenvalues and eigenvectors of a square matrix.
6. svd(): Singular value decomposition of a matrix.

**7. Random Operations:**

1. rand(): Returns an array of random values between 0 and 1.
2. randn(): Returns an array of random values from a standard normal distribution.
3. randint(): Returns an array of random integers within a specified range.
4. choice(): Generates a random sample from a given 1D array.

**8. Set and Conditional Operations:**

1. isnan(): Checks if the elements of the array are NaN (Not a Number).
2. isinf(): Checks if the elements of the array are infinite.
3. isfinite(): Checks if the elements of the array are finite.
4. sign(): Returns element-wise indications of the sign of the elements in an array.

### 1. Accessing and slicing Operations

In [12]:
# 1. Copy
print("1. COPY : ")
import numpy as np
arr = np.array([1, 2, 3])
arr_copy = arr.copy()
arr_copy[0] = 99
print("Original:", arr)  # [1, 2, 3]
print("Copy:", arr_copy)  # [99, 2, 3]
print("-------------------------------")

# 2. View
print("2. VIEW")
arr_view = arr.view()
arr_view[0] = 99
print("Original:", arr)  # [99, 2, 3]
print("View:", arr_view)  # [99, 2, 3]
print("--------------------------------")

# 3. SORT
print("3. SORT")
arr = np.array([3, 1, 2])
arr.sort()
print(arr)  # [1, 2, 3]
print("-----------------------------------")

# 4. RESHAPE
print("4. RESHAPE")
arr = np.array([1, 2, 3, 4])
reshaped = arr.reshape((2, 2))
print(reshaped)  
# [[1, 2]
#  [3, 4]]
print("-----------------------------------")

# 5. APPEND
print("5. APPEND")
arr = np.array([1, 2, 3])
new_arr = np.append(arr, [4, 5])
print(new_arr)  # [1, 2, 3, 4, 5]
print("-----------------------------------")

# 6. INSERT
print("6. INSERT")
arr = np.array([1, 2, 3])
new_arr = np.insert(arr, 1, 99)
print(new_arr)  # [1, 99, 2, 3]
print("-----------------------------------")

# 7. DELETE
print("7. DELETE")
arr = np.array([1, 2, 3])
new_arr = np.delete(arr, 1)
print(new_arr)  # [1, 3]
print("-----------------------------------")

# 8. CONCATENATE
print("8. CONCATENATE")
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
result = np.concatenate((arr1, arr2))
print(result)  # [1, 2, 3, 4]
print("-----------------------------------")

# 9. STACK
print("9. STACK")
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
result = np.stack((arr1, arr2))
print(result)  
# [[1, 2]
#  [3, 4]]
print("-----------------------------------")

# 10. VSTACK
print("10. VSTACK")
result = np.vstack((arr1, arr2))
print(result)  
# [[1, 2]
#  [3, 4]]
print("-----------------------------------")

# 11. HSTACK
print("11. HSTACK")
result = np.hstack((arr1, arr2))
print(result)  # [1, 2, 3, 4]
print("-----------------------------------")

# 12. DSTACK
print("12. DSTACK")
result = np.dstack((arr1, arr2))
print(result)  
# [[[1 3]
#   [2 4]]]
print("-----------------------------------")

# 13. SPLIT
print("13. SPLIT")
arr = np.array([1, 2, 3, 4])
result = np.split(arr, 2)
print(result)  # [array([1, 2]), array([3, 4])]
print("-----------------------------------")

# 14. WHERE
print("14. WHERE")
arr = np.array([1, 2, 3, 4])
result = np.where(arr > 2)
print(result)  # (array([2, 3]),)
print("-----------------------------------")

# 15. SEARCHSORTED
print("15. SEARCHSORTED")
arr = np.array([1, 2, 4, 5])
result = np.searchsorted(arr, 3)
print(result)  # 2
print("-----------------------------------")

# 16. FLATTEN
print("16. FLATTEN")
arr = np.array([[1, 2], [3, 4]])
print(arr.flatten())  # [1, 2, 3, 4]
print("-----------------------------------")

# 17. RAVEL
print("17. RAVEL")
print(arr.ravel())  # [1, 2, 3, 4]
print("-----------------------------------")

# 18. TRANSPOSE
print("18. TRANSPOSE")
print(arr.T)  
# [[1, 3]
#  [2, 4]]
print("-----------------------------------")

# 19. UNIQUE
print("19. UNIQUE")
arr = np.array([1, 2, 2, 3])
print(np.unique(arr))  # [1, 2, 3]
print("-----------------------------------")

# 20. ARGMAX and ARGMIN
print("20. ARGMAX and ARGMIN")
print(arr.argmax())  # 3
print(arr.argmin())  # 0
print("-----------------------------------")

# 21. TILE
print("21. TILE")
print(np.tile(arr, 2))  # [1, 2, 2, 3, 1, 2, 2, 3]
print("-----------------------------------")

# 22. REPEAT
print("22. REPEAT")
print(np.repeat(arr, 2))  # [1, 1, 2, 2, 2, 2, 3, 3]
print("-----------------------------------")

# 23. CLIP
print("23. CLIP")
print(np.clip(arr, 2, 3))  # [2, 2, 2, 3]
print("-----------------------------------")

# 24. MAX and MIN
print("24. MAX and MIN")
print(arr.max())  # 3
print(arr.min())  # 1
print("-----------------------------------")

# 25. SUM
print("25. SUM")
print(arr.sum())  # 8
print("-----------------------------------")

# 26. MEAN
print("26. MEAN")
print(arr.mean())  # 2.0
print("-----------------------------------")

# 27. CUMSUM
print("27. CUMSUM")
print(np.cumsum(arr))  # [1, 3, 5, 8]
print("-----------------------------------")

# 28. PROD
print("28. PROD")
print(np.prod(arr))  # 12
print("-----------------------------------")

# 29. CUMPROD
print("29. CUMPROD")
print(np.cumprod(arr))  # [1, 2, 4, 12]
print("-----------------------------------")

# 30. SORT (Descending using slicing after sort)
print("30. SORT (Descending)")
arr = np.array([3, 1, 2])
arr.sort()
arr_desc = arr[::-1]
print(arr_desc)  # [3, 2, 1]
print("-----------------------------------")

# 31. ROUND
print("31. ROUND")
arr = np.array([1.234, 2.456, 3.678])
rounded = np.round(arr, 1)
print(rounded)  # [1.2, 2.5, 3.7]
print("-----------------------------------")

# 32. ARGWHERE
print("32. ARGWHERE")
arr = np.array([1, 0, 3, 0, 5])
result = np.argwhere(arr > 0)
print(result)  # [[0], [2], [4]]
print("-----------------------------------")


1. COPY : 
Original: [1 2 3]
Copy: [99  2  3]
-------------------------------
2. VIEW
Original: [99  2  3]
View: [99  2  3]
--------------------------------
3. SORT
[1 2 3]
-----------------------------------
4. RESHAPE
[[1 2]
 [3 4]]
-----------------------------------
5. APPEND
[1 2 3 4 5]
-----------------------------------
6. INSERT
[ 1 99  2  3]
-----------------------------------
7. DELETE
[1 3]
-----------------------------------
8. CONCATENATE
[1 2 3 4]
-----------------------------------
9. STACK
[[1 2]
 [3 4]]
-----------------------------------
10. VSTACK
[[1 2]
 [3 4]]
-----------------------------------
11. HSTACK
[1 2 3 4]
-----------------------------------
12. DSTACK
[[[1 3]
  [2 4]]]
-----------------------------------
13. SPLIT
[array([1, 2]), array([3, 4])]
-----------------------------------
14. WHERE
(array([2, 3], dtype=int64),)
-----------------------------------
15. SEARCHSORTED
2
-----------------------------------
16. FLATTEN
[1 2 3 4]
------------------------

#### 2. Arithmetic Operations

In [13]:
# 1. ADDITION
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
sum_result = np.add(arr1, arr2)
print("Add:", sum_result)  # [5, 7, 9]

# 2. SUBTRACTION
sub_result = np.subtract(arr1, arr2)
print("Subtract:", sub_result)  # [-3, -3, -3]

# 3. MULTIPLICATION
mul_result = np.multiply(arr1, arr2)
print("Multiply:", mul_result)  # [4, 10, 18]

# 4. DIVISION
div_result = np.divide(arr1, arr2)
print("Divide:", div_result)  # [0.25, 0.4, 0.5]

# 5. POWER
power_result = np.power(arr1, arr2)
print("Power:", power_result)  # [1, 32, 729]

# 6. MODULO
mod_result = np.mod(arr1, arr2)
print("Modulo:", mod_result)  # [1, 2, 3]

# 7. SQUARE ROOT
sqrt_result = np.sqrt(arr1)
print("Square Root:", sqrt_result)  # [1.        , 1.41421356, 1.73205081]

# 8. ABSOLUTE VALUE
abs_result = np.abs(np.array([-1, -2, -3]))
print("Absolute:", abs_result)  # [1, 2, 3]

# 9. EXPONENTIAL
exp_result = np.exp(arr1)
print("Exponential:", exp_result)  # [ 2.71828183,  7.3890561 , 20.08553692]

# 10. LOGARITHM
log_result = np.log(arr1)
print("Logarithm:", log_result)  # [0.        , 0.69314718, 1.09861229]

# 11. BASE 10 LOGARITHM
log10_result = np.log10(arr1)
print("Log10:", log10_result)  # [0.        , 0.30103   , 0.47712125]

Add: [5 7 9]
Subtract: [-3 -3 -3]
Multiply: [ 4 10 18]
Divide: [0.25 0.4  0.5 ]
Power: [  1  32 729]
Modulo: [1 2 3]
Square Root: [1.         1.41421356 1.73205081]
Absolute: [1 2 3]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Logarithm: [0.         0.69314718 1.09861229]
Log10: [0.         0.30103    0.47712125]


### 3. Comparison Operations

In [14]:
# 1. GREATER
greater_result = np.greater(arr1, arr2)
print("Greater:", greater_result)  # [False, False, False]

# 2. GREATER OR EQUAL
ge_result = np.greater_equal(arr1, arr2)
print("Greater or Equal:", ge_result)  # [False, False, False]

# 3. LESS
less_result = np.less(arr1, arr2)
print("Less:", less_result)  # [True, True, True]

# 4. LESS OR EQUAL
le_result = np.less_equal(arr1, arr2)
print("Less or Equal:", le_result)  # [True, True, True]

# 5. EQUAL
equal_result = np.equal(arr1, arr2)
print("Equal:", equal_result)  # [False, False, False]

# 6. NOT EQUAL
ne_result = np.not_equal(arr1, arr2)
print("Not Equal:", ne_result)  # [True, True, True]

# 7. LOGICAL AND
logical_and_result = np.logical_and(arr1 > 1, arr2 > 1)
print("Logical AND:", logical_and_result)  # [False, True, True]

# 8. LOGICAL OR
logical_or_result = np.logical_or(arr1 > 1, arr2 > 1)
print("Logical OR:", logical_or_result)  # [True, True, True]

# 9. LOGICAL NOT
logical_not_result = np.logical_not(arr1 > 1)
print("Logical NOT:", logical_not_result)  # [True, False, False]


Greater: [False False False]
Greater or Equal: [False False False]
Less: [ True  True  True]
Less or Equal: [ True  True  True]
Equal: [False False False]
Not Equal: [ True  True  True]
Logical AND: [False  True  True]
Logical OR: [ True  True  True]
Logical NOT: [ True False False]


### 4. Statical Operations

In [15]:
import numpy as np

# 1. std(): Computes the standard deviation of array elements.
arr = np.array([1, 2, 3, 4, 5])
std_dev = np.std(arr)
print("Standard Deviation:", std_dev)  # 1.4142135623730951

# 2. var(): Computes the variance of array elements.
variance = np.var(arr)
print("Variance:", variance)  # 2.0

# 3. median(): Computes the median of array elements.
median_val = np.median(arr)
print("Median:", median_val)  # 3.0

# 4. corrcoef(): Computes the Pearson correlation coefficient between two arrays.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
correlation = np.corrcoef(arr1, arr2)
print("Correlation Coefficient:")
print(correlation)  # [[1. 1.] [1. 1.]]

# 5. cov(): Computes the covariance matrix between two arrays.
covariance = np.cov(arr1, arr2)
print("Covariance Matrix:")
print(covariance)  # [[1. 1.] [1. 1.]]

# 6. mean(): Computes the arithmetic mean of array elements.
mean_val = np.mean(arr)
print("Mean:", mean_val)  # 3.0

# 7. cumsum(): Computes the cumulative sum of array elements.
cumulative_sum = np.cumsum(arr)
print("Cumulative Sum:", cumulative_sum)  # [ 1  3  6 10 15]

# 8. prod(): Computes the product of all array elements.
product = np.prod(arr)
print("Product:", product)  # 120

Standard Deviation: 1.4142135623730951
Variance: 2.0
Median: 3.0
Correlation Coefficient:
[[1. 1.]
 [1. 1.]]
Covariance Matrix:
[[1. 1.]
 [1. 1.]]
Mean: 3.0
Cumulative Sum: [ 1  3  6 10 15]
Product: 120


### 5. Set Operations

In [16]:
import numpy as np

# 1. union1d(): Computes the union of two arrays.
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
union = np.union1d(arr1, arr2)
print("Union:", union)  # [1 2 3 4 5 6]

# 2. intersect1d(): Computes the intersection of two arrays.
intersection = np.intersect1d(arr1, arr2)
print("Intersection:", intersection)  # [3 4]

# 3. setdiff1d(): Computes the difference between two arrays.
difference = np.setdiff1d(arr1, arr2)
print("Difference (arr1 - arr2):", difference)  # [1 2]

# 4. setxor1d(): Computes the symmetric difference between two arrays.
symmetric_difference = np.setxor1d(arr1, arr2)
print("Symmetric Difference:", symmetric_difference)  # [1 2 5 6]

Union: [1 2 3 4 5 6]
Intersection: [3 4]
Difference (arr1 - arr2): [1 2]
Symmetric Difference: [1 2 5 6]


### 6. Linear Algebra Operations

In [17]:
import numpy as np

# 1. dot(): Computes the dot product of two arrays.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
dot_product = np.dot(arr1, arr2)
print("Dot product:", dot_product)  # 32 (1*4 + 2*5 + 3*6)

# 2. matmul(): Matrix multiplication of two arrays.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
matrix_multiplication = np.matmul(arr1, arr2)
print("Matrix multiplication:\n", matrix_multiplication)
# [[19 22]
#  [43 50]]

# 3. cross(): Computes the cross product of two arrays.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
cross_product = np.cross(arr1, arr2)
print("Cross product:", cross_product)  # [-3  6 -3]

# 4. inv(): Computes the inverse of a square matrix.
arr = np.array([[1, 2], [3, 4]])
inverse_matrix = np.linalg.inv(arr)
print("Inverse of the matrix:\n", inverse_matrix)
# [[-2.   1. ]
#  [ 1.5 -0.5]]

# 5. eig(): Computes the eigenvalues and eigenvectors of a square matrix.
arr = np.array([[4, -2], [1,  1]])
eigenvalues, eigenvectors = np.linalg.eig(arr)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# 6. svd(): Singular value decomposition of a matrix.
arr = np.array([[1, 2], [3, 4]])
U, S, Vt = np.linalg.svd(arr)
print("U:\n", U)
print("Singular values:", S)
print("Vt:\n", Vt)

Dot product: 32
Matrix multiplication:
 [[19 22]
 [43 50]]
Cross product: [-3  6 -3]
Inverse of the matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular values: [5.4649857  0.36596619]
Vt:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


### 7. Random Operations

In [18]:
import numpy as np

# 1. rand(): Returns an array of random values between 0 and 1.
rand_arr = np.random.rand(3, 2)
print("Random values between 0 and 1:\n", rand_arr)
# Output: A 3x2 array of random values between 0 and 1

# 2. randn(): Returns an array of random values from a standard normal distribution.
randn_arr = np.random.randn(3, 2)
print("Random values from standard normal distribution:\n", randn_arr)
# Output: A 3x2 array of random values drawn from a standard normal distribution

# 3. randint(): Returns an array of random integers within a specified range.
randint_arr = np.random.randint(1, 10, size=(3, 2))
print("Random integers between 1 and 10:\n", randint_arr)
# Output: A 3x2 array of random integers between 1 and 10 (exclusive)

# 4. choice(): Generates a random sample from a given 1D array.
arr = np.array([10, 20, 30, 40, 50])
random_sample = np.random.choice(arr, size=3, replace=False)
print("Random sample from array:\n", random_sample)
# Output: A 1D array of 3 random values selected from arr without replacement

Random values between 0 and 1:
 [[0.59676489 0.38649249]
 [0.6889379  0.58801568]
 [0.56486777 0.25871698]]
Random values from standard normal distribution:
 [[-0.9495959  -0.77933997]
 [ 0.26025655  0.42637213]
 [-0.27854245  0.35480033]]
Random integers between 1 and 10:
 [[8 8]
 [8 2]
 [1 7]]
Random sample from array:
 [20 10 40]


### 8. Set and Conditional Operations

In [19]:
import numpy as np

# 1. isnan(): Checks if the elements of the array are NaN (Not a Number).
arr_nan = np.array([1, 2, np.nan, 4])
is_nan = np.isnan(arr_nan)
print("isnan() result:\n", is_nan)
# Output: [False False  True False], since only np.nan is NaN

# 2. isinf(): Checks if the elements of the array are infinite.
arr_inf = np.array([1, 2, np.inf, -np.inf])
is_inf = np.isinf(arr_inf)
print("isinf() result:\n", is_inf)
# Output: [False False  True  True], as np.inf and -np.inf are infinite

# 3. isfinite(): Checks if the elements of the array are finite.
arr_finite = np.array([1, 2, np.nan, np.inf])
is_finite = np.isfinite(arr_finite)
print("isfinite() result:\n", is_finite)
# Output: [ True  True False False], as np.nan and np.inf are not finite

# 4. sign(): Returns element-wise indications of the sign of the elements in an array.
arr_sign = np.array([-10, 0, 5])
sign_arr = np.sign(arr_sign)
print("sign() result:\n", sign_arr)
# Output: [-1  0  1], where -1 indicates negative, 0 indicates zero, and 1 indicates positive

isnan() result:
 [False False  True False]
isinf() result:
 [False False  True  True]
isfinite() result:
 [ True  True False False]
sign() result:
 [-1  0  1]


# -------END-------------